---
title: Digital Preservation Step By Step
author: Orbis Cascade Alliance 
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: ccd-digitalpreservationwg@orbiscascade.org
description: "Steps to help you improve your institution's digital preservation practices."
baseurl: ''
url: ''
github_username: orbiscascadeccd
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
