---
title: Digital Preservation Step By Step
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: dbecker@uidaho.edu
description: 'A site to help you improve your digital preservation practices

'
baseurl: ''
url: ''
github_username: dcnb
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
